name: JavaScript Lint
on: push
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: yarn install
    - run: yarn lint
